### ISSUE TITLE
new entry for addons lists

### ISSUE THREAD

**Issue by torkus** [antiwinter/wowa#1]
hey! can I get a mention in your addon managers list?

https://github.com/ogri-la/wowman

**Comment by antiwinter** [comment]
> t?

sure, thanks

**Comment by antiwinter** [comment]
> hey! can I get a mention in your addon managers list?
> 
> https://github.com/ogri-la/wowman

sure, thanks

**Comment by torkus** [comment]
ha! thanks :) reminds me of the old days of webrings.
