### ISSUE TITLE
crash trying to update

### ISSUE THREAD

**Issue by gcaliber** [antiwinter/wowa#15]
I'm getting this crash when trying to update.

>  ↓ cannonpalms/FasterLooting [github] is already up to date [skipped]
>   ⠏ omni-cc [curse] checking for updates...
>   ↓ fusionpit/WhatsTraining [github] is already up to date [skipped]
>   ⠏ monkey-quest [curse] checking for updates...
>   ⠏ AeroScripts/QuestieDev [github] downloading...
>   ↓ 24924-RealMobHealth [mmoui] is already up to date [skipped]
>   ↓ Aviana/YaHT [github] is already up to date [skipped]
>   ↓ 24958-AuctionatorClassicquickfix [mmoui] is already up to date [skipped]
>   ⠏ 24906-123 [mmoui] downloading...
>   ↓ 25160-ItemTooltipProfessionIcons [mmoui] is already up to date [skipped]
>   ⠴ monkey-buddy [curse] checking for updates...
>   ↓ 25109-LetMeCast [mmoui] is already up to date [skipped]
>   ⠴ advancedinterfaceoptions [curse] checking for updates...
>   ⠼ elvui-adibags [curse] checking for updates...
>   ↓ 2-ElvUI [tukui] is already up to date [skipped]
>   ⠼ leatrix-plus-classic [curse] checking for updates...
>   ⠹ vendor-price [curse] checking for updates...
>   ⠙ atlaslootclassic [curse] checking for updates...
>     24936-NugRunningClassic waiting...
>     guidelime waiting...
>     deadly-boss-mods waiting...
>     leatrix-maps-classic waiting...
> /home/mike/.npm-global/lib/node_modules/wowa/lib/unzip.js:10
>     if (err) throw err
>              ^
> 
> Error: end of central directory record signature not found
>     at /home/mike/.npm-global/lib/node_modules/wowa/node_modules/yauzl/index.js:187:14
>     at /home/mike/.npm-global/lib/node_modules/wowa/node_modules/yauzl/index.js:631:5
>     at /home/mike/.npm-global/lib/node_modules/wowa/node_modules/fd-slicer/index.js:32:7
>     at FSReqCallback.wrapper [as oncomplete] (fs.js:478:5)
>

**Comment by antiwinter** [comment]
Add a fix for this [01be21a4f144cc1f5449c0893597d988bdec78a0](https://github.com/antiwinter/wowa/commit/01be21a4f144cc1f5449c0893597d988bdec78a0)

**Comment by antiwinter** [comment]
Hi, can you please tell me which addon is causing this crash? After this fix, I've attached an error message to the crash-causing addon when updating.
