### ISSUE TITLE
Change wow directory

### ISSUE THREAD

**Issue by An7hrax** [antiwinter/wowa#19]
Cant find any way to set the directory that wowa will use to find it's addons.
Tried to edit the config.js but with no success.

I'm using Linux so that's why the path is not working.

**Comment by antiwinter** [comment]
Or if still failed, please paste the error message for my debugging

**Comment by An7hrax** [comment]
Alright, new to the ndoe world :).
Thanks for clarifying the path of the wow_path.txt

Works now.

**Comment by antiwinter** [comment]
Happy to hear that, then I am going to close this issue
