### ISSUE TITLE
Feature request: PTR (and futher Beta) support

### ISSUE THREAD

**Issue by CyanoHao** [antiwinter/wowa#21]
The PTR client is located at `World of Warcraft/_ptr_`, and it’s usually okay to install addons from Curse’s Retail release channel.

The Beta client will be likely located at `World of Warcraft/_beta_`. There can be some imcompatable changes, and thus Curse’s Retail alpha or beta channel may be preferred.

P.S. I can provide an account with PTR access if necessary.

**Comment by antiwinter** [comment]
It's okay to add more game versions, but the important thing is to get the correct corresponding addons installed. So for `_ptr_` **wowa** should provide the `_retail_` version addon.

But for `_beta_`, I think the alpha and beta on curse means "the addon is in its alpha and beta stage for the `_retail_` game version", am I wrong?

**Comment by CyanoHao** [comment]
Yeah, exactly.

**Comment by antiwinter** [comment]
I'm wondering how BLZ will name the folders for **classic prt** and **classic beta**

**Comment by CyanoHao** [comment]
Folders of classic beta was simply `_classic_beta_`.
I'm not sure whether there will be classic prt, but if there is, it may be `_classic_ptr_`.

**Comment by antiwinter** [comment]
Supported. 
I am going to close this issue. Feel free to reopen it if necessary.
