### ISSUE TITLE
unable to add any curse addons

### ISSUE THREAD

**Issue by gcaliber** [antiwinter/wowa#23]
All curse addons say skipped/unavailable when I try to add them. They can be found in search, but will say unavailable when I try to install them.

**Comment by antiwinter** [comment]
Can you find them by `wowa info`? It seems you are blocked by CDN/Cloudflare protection. I've changed curse solution from scraping to API, which can solve this problem, But still not released.

**Comment by antiwinter** [comment]
I have released a new version, please have a try

**Comment by antiwinter** [comment]
If still not working, try `wowa update --db`

**Comment by gcaliber** [comment]
Just updated to the latest release and its now working.
