### ISSUE TITLE
Addon not showing updates

### ISSUE THREAD

**Issue by alexboutros** [antiwinter/wowa#24]
I have not run `wowa update` yet today, and I know there are addon updates waiting, but `wowa update` says there is nothing to update. Also `wowa info addon-name` never works. I've tried it with TomTom, DBM-Core, and other addons that `wowa ls` shows. It always returns "Not Available".

**Comment by antiwinter** [comment]
Can you please try your failed commands (`wowa ls`, `wowa info xxx`, `wowa update`) again and paste the full log here for my debugging?

**Comment by alexboutros** [comment]
Well I have no idea what changed, but everything seems to be working now. If the issue happens again I will try and get you more info.

**Comment by antiwinter** [comment]
:astonished:
