### ISSUE TITLE
Implement abritrary git repositories

### ISSUE THREAD

**Issue by Flat** [antiwinter/wowa#25]
Instead of just GitHub support allow any full git URL path to be installed as an add-on.

Examples of installation (non exhaustive):
`wowa install http://git.example.com/user/addon branch`
`wowa install http://git.example.com/user/addon/branch`
`wowa install-git http://git.example.com/user/addon#branch`
etc.

While this won't allow metadata from apis unless implemented as individual CVS sites it allows users to install add-ons from any potential repository such as the tukui development repositories that may contain bug fixes or features that are available before a release on the conventional add-on sites.

**Comment by antiwinter** [comment]
Well, this is possible.  But the information provided by `wowa info` would be very limited for arbitrary repos.

**Comment by antiwinter** [comment]
[Supported](https://github.com/antiwinter/wowa#installing-an-addon-from-arbitrary-repo)
