### ISSUE TITLE
Allow Pinning of Addons to hold updates

### ISSUE THREAD

**Issue by Praxsidian** [antiwinter/wowa#27]
It would be a very helpful feature to allow us to pin add-ons at certain version, so they are not updated. Some UI's such was realui on wowinterface have a few add-ons that need stay pinned at their current update because the author has altered code that will break the add-on if it is updated.

**Comment by antiwinter** [comment]
Good suggestion. I once thought about this but forgot during the latter development.

**Comment by antiwinter** [comment]
```
wowa pin deadly-boss-mods       # addon is pinned to it's current version
wowa unpin deadly-boss-mods     # addon is unpinned
```

`wowa ls -l` displays an exclaimation mark before version, incicating that addon is pinned.
