### ISSUE TITLE
wowaads.json no such file or directory

### ISSUE THREAD

**Issue by Praxsidian** [antiwinter/wowa#28]
This is a new issue I have gotten. I just installed a fresh copy of manjaro with the kde desktop. I was attempting to download my add-ons to set up WoW and I keep getting this error when I try to do install, import, remove, etc any add-on. You can find a screenshot that I am going to attach that will hopefully help with this issue.

![Screenshot_20191212_050208](https://user-images.githubusercontent.com/46389541/70708442-1c198100-1ca0-11ea-80a2-6896759bc8ab.png)

**Comment by antiwinter** [comment]
It seems your **wow_path.txt** configuration is wrong. The path must end at the `_retail_` or `_classic_` part.

### Wrong:
```
/mnt/Games/WoW/drive_c/Program Files (x86)/World of Warcraft/_retail_/Interface/Addons
```

### Correct:
```
/mnt/Games/WoW/drive_c/Program Files (x86)/World of Warcraft/_retail_
```

**Comment by Praxsidian** [comment]
I feel like an idiot hahaha.... thanks antiwinter you're an incredible dev and I love wowa. Keep up the wonderful work.
