### ISSUE TITLE
"UnhandledPromiseRejectionWarning: Error: EISDIR: illegal operation on a directory" while downloading addons

### ISSUE THREAD

**Issue by h1ghb1rd** [antiwinter/wowa#3]
Some addons are giving me the errors during installation, I have no idea what the cause might be, any idea?

I'm on 1809 x64, German, Powershell Version 5.1.17763.592. 
Please let me know if you need more information about my system. Installed about 15 other addons from WoWInterface, Curse and Github and all works fine there.

` PS C:\Users\Tim> wowa add sellableitemdrops
  / sellableitemdrops @0.4.12 [curse] downloading... 100%
(node:16424) UnhandledPromiseRejectionWarning: Error: EISDIR: illegal operation on a directory, open 'C:\Users\Tim\AppData\Roaming\wowa\sellableitemdrops\dec\SellableItemDrops\Libs'
(node:16424) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
  | sellableitemdrops @0.4.12 [curse] downloading... 100%
Batchvorgang abbrechen (J/N)? J`

Deleting the the folder "C:\Users\Tim\AppData\Roaming\wowa\sellableitemdrops\dec\SellableItemDrops" does not help:
` PS C:\Users\Tim> wowa add sellableitemdrops
  / sellableitemdrops @0.4.12 [curse] downloading... 100%
(node:16460) UnhandledPromiseRejectionWarning: Error: EISDIR: illegal operation on a directory, open 'C:\Users\Tim\AppData\Roaming\wowa\sellableitemdrops\dec\SellableItemDrops\Libs\LibParse\Libs\tests'
(node:16460) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
  \ sellableitemdrops @0.4.12 [curse] downloading... 100%`

More examples:

`PS C:\Users\Tim> wowa add 25040-BetterAlign
  \ 25040-BetterAlign @1.0.0 [wowinterface] downloading... 100%
(node:440) UnhandledPromiseRejectionWarning: Error: EISDIR: illegal operation on a directory, open 'C:\Users\Tim\AppData\Roaming\wowa\25040-BetterAlign\dec\BetterAlign\.git'
(node:440) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:440) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections   \ 25040-BetterAlign @1.0.0 [wowinterface] downloading... 100%`

` PS C:\Users\Tim> wowa add classicon - classicon @v0.1 [curse] downloading... 100%
(node:26512) UnhandledPromiseRejectionWarning: Error: EISDIR: illegal operation on a directory, open 'C:\Users\Tim\AppData\Roaming\wowa\classicon\dec\ClassIcons\Libs\LibBabble-CreatureType-3.0'
(node:26512) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26512) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejection  - classicon @v0.1 [curse] downloading... 100% `

**Comment by antiwinter** [comment]
Yes, this can be reproduced by installing **sellableitemdrops** on my macOS.

This seems to be an issue of the package **decompress-unzip** as described in their [repo](https://github.com/kevva/decompress-unzip/issues/12). But it seems their repo is not maintained anymore.

So I do a workaround at this moment to avoid this issue (I have compared the installed files with manually unzipped files and they are the same).

In the future, I may look for another decompress package to replace the current one.
