### ISSUE TITLE
nolib version of some curse addons being installed

### ISSUE THREAD

**Issue by Llamatron2112** [antiwinter/wowa#30]
It looks like wowa installs the -nolib version of some addons hosted on Curse, at least it's doing it for me with Ark Inventory and Chocolate Bar, and they stop working as the libs they depend on are not here.

Their page : 
https://www.curseforge.com/wow/addons/ark-inventory
https://www.curseforge.com/wow/addons/chocolatebar

Might be others, but thoses two broke after a wowa update.

EDIT: Forgot to mention it is for classic version, didn't test with retail as I don't have it installed

**Comment by Llamatron2112** [comment]
I just found the @version you can add behind a package name to install a specific version, for example for ArkInventory: `wowa add curse:ark-inventory@3.09.12-Classic` will install the version with libs. You can see which versions are available by looking at the "Files" tab on the website.

Would be nice if the readme mentionned this, and also the --anyway flag.

**Comment by antiwinter** [comment]
Thank you for the feedback.

I've just submitted a commit to filter out the `-nolib` versions. I would do some tests later and make a release.

The versions **wowa** gets from API is not exactly matched with the list you can see on the website, so I didn't mention it in the readme...

**Comment by antiwinter** [comment]
Version is released, sorry for late responding, I was busy leveling my mage...

**Comment by Llamatron2112** [comment]
I need to wait for some ark-inventory update to see if it is fixed for me too, but right now I notice there's a warning about a deprecated syntax at each wowa command `[@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead`

**Comment by Llamatron2112** [comment]
It doesn't install the nolib version anymore, thanks for your work !

**Comment by antiwinter** [comment]
OK, I am going to close this issue and I will pay attention to the deprecated warning.
