### ISSUE TITLE
Some Curse classic addons won't install

### ISSUE THREAD

**Issue by Llamatron2112** [antiwinter/wowa#33]
Since a few days I got a few addons for which wowa doesn't seem to detect there's a download for classic. For example https://www.curseforge.com/wow/addons/cooldown-watcher or https://www.curseforge.com/wow/addons/smartloot-for-classic , it just answers "not available [skipped]" when trying to install with their name or their url.

**Comment by antiwinter** [comment]
Thank you for your feedback. This issue is fixed.

You can update **wowa** to latest version (1.3.10) and use command `wowa update --db` to force update database and then install **cooldown-watcher** again.

**Comment by Llamatron2112** [comment]
Yes it seems to be fixed, thanks again for your great work :)
