### ISSUE TITLE
Arbritrary github repo not working

### ISSUE THREAD

**Issue by willfurstenau** [antiwinter/wowa#37]
Looking to set up my addons for the Shadowlands beta, I was able to add ElvUI via `wowa install https://git.tukui.org/ElvUI/ElvUI.git@beta`, however when I try to add WeakAuras, it fails to install 
```
wowa install https://github.com/Weakauras/Weakauras2.git@shadowlands

Installing addon...

  ↓ Weakauras/Weakauras2.git @shadowlands [github] not available [skipped]

0 addons installed
✨  done in 0s.
```
it doesn't seem to matter which branch I pick or even if I pick a release version. 

If there's any log or anything I can send you to assist let me know

**Comment by antiwinter** [comment]
Sorry that my doc is not very clear. This arbitrary repo does not include github. For github, you'll need to use slash `/` to indicate branches.

```
wowa install Weakauras/Weakauras2/shadowlands
```

or

```
wowa install https://github.com/Weakauras/Weakauras2/shadowlands
```

**Comment by willfurstenau** [comment]
Awesome, thanks! I can open a PR to clarify the doc later today. Also, just a suggestion, but it'd be nice if when I ran `wowa list` if it showed what version the addon was using, specifically when using a non default version

**Comment by antiwinter** [comment]
> Awesome, thanks! I can open a PR to clarify the doc later today. Also, just a suggestion, but it'd be nice if when I ran `wowa list` if it showed what version the addon was using, specifically when using a non default version

`wowa ls -l` or `wowa list -l`

**Comment by antiwinter** [comment]
I am going to close this, if any questions, feel free to open another issue.
