### ISSUE TITLE
Allow installation of non-supported versions

### ISSUE THREAD

**Issue by dkrutsko** [antiwinter/wowa#4]
Hey there, great application! I did find something very annoying with classic though.

There are a lot of addons on curse that work with classic but don't advertise themselves as working with classic. Installing these with WoWA doesn't work as it gives me a `version is not available` message. In these cases I would like to have a `--flag` or just have WoWA download the latest retail version anyway.

**Comment by antiwinter** [comment]
Thank you for the feedback.

For classic addons, it is really annoying at this moment. Because of the web sites do not have a common standard.

Your suggestion will be considered, I think I can figure out a solution before 8/27 : )

**Comment by antiwinter** [comment]
@dkrutsko David, could you please give me some addons that are not advertising classic but are actually compatible. I'm doing some tests.

**Comment by dkrutsko** [comment]
Sure, try these, if you need more, I got my own addon collection going [here](https://dave.krutsko.net/classic-addons).

```bash
wowa add cellular
wowa add cinematiccanceler
wowa add copypasta
```

**Comment by antiwinter** [comment]
Wow, you've really made a great collection!

Yes, the three addons you listed do not have classic version indicated by websites. Do you use them by modifying the **.toc** file or do you check the **Use outdated addons** in the game?

**Comment by antiwinter** [comment]
I'm looking into TukUI

**Comment by antiwinter** [comment]
This feature is supported.

```
wowa add cellular cinematiccanceler copypasta --anyway
```

Well `wowa update` will still try to get the correct version for these addons unless you use `wowa update --anyway`. Other addons that are installed without `--anyway` flag are not effected, which means **wowa** always check correct version for them.

**Comment by dkrutsko** [comment]
Hey, thanks for implementing this! I always check *Use outdated addons*, especially since a lot of the addons I use don't get regular updates throughout an expansion but continue to work properly.

And yes, this is pretty much how I implemented it in #7 except I used `--force`.

**Comment by antiwinter** [comment]
Support for TukUI is also added

**Comment by dkrutsko** [comment]
Super nice, thanks. I'll close this issue.

**Comment by antiwinter** [comment]
Yes, the key for classic is different from retail, switch to classic mode and then use ‘wowa search tukui’ to determine the correct key
