### ISSUE TITLE
How do you search the tukui repo?

### ISSUE THREAD

**Issue by Brin-o** [antiwinter/wowa#41]
Hey,
how do you go about searching the tuk ui repo? Do I have to manually add their git repos to my wowa to be able to use them? 

I seem to only get results from curse and I can't find any documentation on how to switch the "source".

![elv](https://user-images.githubusercontent.com/49071768/93060853-04c65480-f673-11ea-9057-e8dbb23ed488.gif)

**Comment by antiwinter** [comment]
You can add a source indicator to overwrite the default priority (curse is the top 1 preferred source by default)

```
wowa search tukui:elv
```

**Comment by Brin-o** [comment]
Fantastic! Thank you :)
