### ISSUE TITLE
Problem installing from curseforge git repo

### ISSUE THREAD

**Issue by gcaliber** [antiwinter/wowa#43]
Trying to install an addon from its curseforge git repo causes wowa to install the addon twice; once with curse as the source and once with git as the source. Not sure if this should even be supported, but it should probably only install it one way if you try to do this.

**Comment by antiwinter** [comment]
Do you have an example?

**Comment by gcaliber** [comment]
Oops, thought I was just copying a link when it also had the addon key after it. Works fine.
