### ISSUE TITLE
Installing from git fails to get a valid date for last update

### ISSUE THREAD

**Issue by gcaliber** [antiwinter/wowa#44]
Listing addons installed with a git source always shows invalid date for last update.

**Comment by antiwinter** [comment]
Do you mean the last column when `wowa ls -l`? Do you have an example

**Comment by gcaliber** [comment]
https://gitlab.vuhdo.io/vuhdo/vuhdo  master            git     Invalid date

Anything on gitlab that I have tried does this. Curseforge git repo does the same thing.

**Comment by antiwinter** [comment]
Fixed in (6da749f)
