### ISSUE TITLE
Incorrect update date from github

### ISSUE THREAD

**Issue by gcaliber** [antiwinter/wowa#45]
When doing wowa ls -l there is an incorrect Update date for several of my addons with github sources.

Examples:
Stanzilla/AdvancedInterfaceOptions - Last commit was 2020-08-21 and last release was 2020-01-23, but wowa shows 2016-06-26
funkydude/BadBoy - Last commit and release was on 2019-09-04, but wowa shows 2016-08-01
Tercioo/Details-Damage-Meter - Last commit was 2020-10-04 and last release was 2020-08-11, but wowa shows 2019-12-15

**Comment by antiwinter** [comment]
This is fixed in (6da749f)
