### ISSUE TITLE
Removing WowInterface addons doesn't appear to work

### ISSUE THREAD

**Issue by dkrutsko** [antiwinter/wowa#5]
One thing I found is that installing a wowinterface addon, and then deleting it, doesn't appear to work.

```
wowa add wowinterface:19390
wowa rm  wowinterface:19390
```

**Comment by antiwinter** [comment]
Did you try other wowinterface addons? I think it should be something like `wowa add wowinterface:19390-KuiNameplates`

For removing, maybe you can try `wowa rm 19390-KuiNameplates`, which can be determined from `wowa ls`

**Comment by dkrutsko** [comment]
I'll try, I was removing everything after the `-` before but it turned out to be a huge problem.

**Comment by dkrutsko** [comment]
I haven't tried yet, but I'm sure it's fine. I'll reopen if there's a problem.
