### ISSUE TITLE
Cannot install ElvUI from tukui - unzip failed

### ISSUE THREAD

**Issue by mervyn-mccreight** [antiwinter/wowa#51]
I'm trying to install ElvUI using wowa, but I fail to do so (`unzip failed`).
Am I doing something wrong here? 😅 

#### 1. Search for ElvUI
```
wowa search tukui:elvui

15 results from tukui

ElvUI (https://www.tukui.org/addons.php?id=0)
  key: 0-1ElvUI download: 1.0m version: 02/18/2021

(...)
```

#### 2. Add/install
```
 wowa install tukui:0-1ElvUI

Installing addon...

  ↓ 0-1ElvUI [tukui] unzip failed [skipped]

0 addons installed
✨  done in 6s.
```

Doing the same without specifying the repository results in the same
```
 wowa install 0-1ElvUI

Installing addon...

  ↓ 0-1ElvUI [tukui] unzip failed [skipped]

0 addons installed
✨  done in 7s.
``` 
### Versions I am using
```
wowa --version
1.3.13

node --version
v14.15.3
```

### Additional information
I managed to install it directly using the git-repository reference, but I am still wondering if this is the way to do it or if the above should have also worked.

**Comment by antiwinter** [comment]
I am too busy these days to check **wowa**. But your issue is so beautifully written, so I have to have a look at it :)

And... Found a bug in my code. I'll release the new version soon. Thank you for reporting.
