### ISSUE TITLE
A few more aliases for the commands

### ISSUE THREAD

**Issue by dkrutsko** [antiwinter/wowa#6]
Sorry for the overload of issues but I've been experimenting with WoWA a lot and I would like to see a few more alises for some of these commands. Specifically:

```
# Installation
wowa get addon

# Removal
wowa remove addon
wowa uninstall addon
```

**Comment by antiwinter** [comment]
I am using [commander](https://github.com/tj/commander.js) which does not support multiple aliases at this moment. Someone has raised an issue [there](https://github.com/tj/commander.js/issues/531).

Let's just follow their progress

**Comment by antiwinter** [comment]
finally
https://github.com/antiwinter/wowa/commit/b459df7146a2efb331387d288fa5a044ae4986dd
